### ISSUE TITLE
сделать красиво

### ISSUE THREAD

**Issue by Libirdie** [sainthardawa/toryart#102]
https://gyazo.com/63cb3a2a1590a8435883ba06d0a4eb63
http://toryart.com.ua/shop/

**Comment by mrYegor** [comment]
http://prntscr.com/98oo3q

**Comment by mrYegor** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/14030293/11473779/252eed4a-977d-11e5-86e1-aa2c4fadba14.png)
