### ISSUE TITLE
сделать сортировку категорий на стр. Каталог

### ISSUE THREAD

**Issue by Libirdie** [sainthardawa/toryart#28]
http://valentingunko.com.ua/toryart/shop/

**Comment by sainthardawa** [comment]
@Libirdie сортировку по чему?

**Comment by Libirdie** [comment]
Авторские букеты
Композиции в корзинках
Композиции в коробках
Цветы поштучно
Свадебные букеты
Мужские букеты
Подарки
Открытки и конверты
К праздникам
