### ISSUE TITLE
translate social login page text

### ISSUE THREAD

**Issue by Libirdie** [sainthardawa/toryart#69]
Экономьте время в следующий раз при оформлении заказа, связав свой аккаунт c вашей " "социальной сети. Нет необходимости помнить еще один логин и пароль.
http://prntscr.com/917jek

**Comment by Libirdie** [comment]
Экономьте время в следующий раз при оформлении заказа, связав свой аккаунт c вашей " "социальной сети. Нет необходимости помнить еще один логин и пароль.

**Comment by mrYegor** [comment]
done
